# `.groupby()` & `.value_counts()`

## `.groupby()`

<p align="center"><img src="https://miro.medium.com/v2/resize:fit:1400/1*w2oGdXv5btEMxAkAsz8fbg.png" width="1000"></p>

Generally speaking, this type of `pandas` operation follows a `split-apply-combine` pattern. `pandas` syntax combines the `apply` and `combine` steps.
- First we `split` the data into groups.
- Then we `apply` a function to each group independently.
- Then we `combine` the function results into a data structure.

For example, let's say we wanted to calculate average age by marital status.

In [ ]:
df[['MAR', 'AGEP']].groupby('MAR').mean() # average age by marital status

The first set of brackets (`[]`) isolates a subselection with only these two columns. Then we apply the `.groupby()` method to the `MAR` column to calculate `.mean()` for the `AGEP` values.

Another way to calculate average age by marital status, using a slightly different syntax:

In [ ]:
df.groupby('MAR')['AGEP'].mean() # average age by marital status

In this alternate example, the column name in the `.groupby()` parenthesis specifies the column to group by. The column name in brackets (`[]`) specifies the column to perform the mathematical function on.

## Additional Resources

- [Pandas "Group by" documentation](https://pandas.pydata.org/pandas-docs/stable/user_guide/groupby.html#groupby)
- [Pandas documentation, "Group by: split-apply-combine"](https://pandas.pydata.org/pandas-docs/stable/user_guide/groupby.html#groupby)

## `.value_counts()

We can also count the number of records by category using `.value_counts()`. The `.value_counts()` method returns the number of records for each category in a column.

Let's say we want to know the number of records for each marital status. Thinking through the underlying logic, we need a program that groups by marital status and calculates the number of records for each unique value.

In [ ]:
df['MAR'].value_counts() # count number of records for each marital status unique value

We could also break out these steps using a combination of `.groupby()` and `.count()`.

In [ ]:
df.groupby('MAR')['MAR'].count() # count number of records for

In the second example, we are explicitly categorizing the data by category in the `MAR` column, then performing a `.count()` operation on the records for each `MAR` category.

## Putting It All Together

A few key takeaways:
- We can calculate aggregate statistics for entire rows or columns
- `.groupby()` follows a `split-apply-combine` pattern
- `.value_counts()` can be a shorthand for getting the number of entries for each category in a field